### ISSUE TITLE
[Bug]: Worker fails to provide inputs to tsc

### ISSUE THREAD

**Issue by paullewis** [aspect-build/rules_ts#281] opened 2022-12-20 14:33 UTC
### What happened?

Building a large project with `ts_project` fails for me with the following error (some paths redacted):

```
ERROR: /path/foo/BUILD.bazel:66:10: Compiling TypeScript project @//path/foo/types:Foo_typings
[tsc -p tsconfig.bazel.json] failed: (Exit 1): tsc_worker.sh failed: error executing command (from target
 //path/foo/types:Foo_typings) 
bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/npm_typescript/tsc_worker.sh @bazel-out/darwin_arm64-fastbuild/bin/path/foo/types:Foo.d.ts-0.params


error TS18003: No inputs were found in config file '/private/var/tmp/_bazel_user/hash/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/tsconfig.bazel.json'. 
Specified 'include' paths were '["**/*"]' and 'exclude' paths were '[]'.
```

What's odd is that it will fail on different _typings targets on successive runs.

If I set `supports_workers` to `False` then everything comes right again.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: 5.4.0 and 6.0.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: rules_ts-1.0.X

Language(s) and/or frameworks involved: TS

### How to reproduce

I'm having a hard time reproducing the behavior on small projects - I'll keep digging.

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by paullewis** [comment] 2022-12-20 14:41
All the TS files that fail seem to export types only, i.e., they don't have anything in them beyond types.

If I manually step in and build the `_typecheck` for each then go again, eventually it will get to a complete build.

So... something around type-only files and workers? Not that I can repro the issue with a small number of files, mind 🤔

**Comment by alexeagle** [comment] 2022-12-20 19:20
Feeling increasingly to me like we should have workers off by default. I think there are still a number of statefulness bugs in there. Since we have faster transpilers to support the development loop, I think it's not that bad to turn off supports_workers globally.

**Comment by paullewis** [comment] 2022-12-21 08:57
For what it's worth I agree. In general I use SWC as the day-to-day transpiler with `_typecheck` and `_typecheck_test` being picked up via `bazel build //...` and `bazel test //...` as an additional "belt and braces" / "I didn't hold the types wrong" check.

I do appreciate the speed boost of having a persistent worker, it's definitely nice, but if it's proving buggy I'd just have to switch it off.

**Comment by gregmagolan** [comment] 2023-02-05 16:57
@thesayyn landed a large worker refactor that should resolve the underlying issue here. @paullewis When you have some time can you try re-enabling workers in your repository with the latest version of rules_ts?

**Comment by alexeagle** [comment] 2023-05-09 00:02
Since we didn't hear back from @paullewis I'll assume that large refactor fixed it. Someone can file again if it's still reproducible.

**Closed by alexeagle** 2023-05-09 00:02 UTC
Labels: bug, confirmation needed
