### ISSUE TITLE
[FR]: Ability to swap out the typescript transpiler based on config. 

### ISSUE THREAD

**Issue by charlesoconor** [aspect-build/rules_ts#276] opened 2022-12-16 22:34 UTC
### What is the current behavior?

Currently, the `ts_project` rule/macro takes a `transpiler` argument which needs to be a rule or function. This allows for switching out which compiler you want to use. 

### Describe the feature

Having it take a macro for `transpiler` means that you can't use a `select` argument to pick which version of the compiler we are using. e.g. 

```
    src = select({
        "//some_config": "swc",
        "default": "tsc",
    }),
```

I want to give the ability to developers who want a tight run test loop to allow them to run `swc` when they want and switch back to `tsc` for CI and when they want the types to be checked. With a flag e.g 

```
bazel test --//config:swc_on ... 
```

I would be happy to work on this change if I could get some code pointers around and a history lesson on why this decision was made. Thank you! 

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by alexeagle** [comment] 2022-12-20 19:19
ts_project is a macro because it wants to predict the output paths, so they can be predeclared labels and you can do something like `entry_point = "index.js"` in a later rule, where `index.ts` was an input to the `ts_project`.

I don't think you need to use [configurable attributes](https://bazel.build/docs/configurable-attributes) for this. Your problem description seems like it's just unaware that type-checking still happens with `tsc` even if the transpiler attribute is using swc. The `.d.ts` outputs still require `tsc` to successfully type-check, and you build the `[name]_typecheck` target to request typechecking.

So I bet this is already working as intended. Read https://docs.aspect.build/aspect-build/rules_ts/v1.0.4/docs/transpiler.html#macro-expansion and let me know if there's actually some use case which isn't already supported.

**Comment by charlesoconor** [comment] 2022-12-22 07:26
I want to have the ability to use `tsc` and `swc` as alternatives to the transpiler with a single rule or macro. Based on config so developers can switch out based on speed. As far as I'm aware, `swc` doesn't have the ability to output declaration files. To use `_typcheck` target's as well, I'd need to build out what other first-party libs any given library depends on and run actual `tsc` over them to get the declaration files for them. For example, If I have a project like this 

```
├── BUILD.bazel
├── WORKSPACE
├── baz
│   ├── BUILD.bazel
│   └── index.ts
├── foo
│   ├── BUILD.bazel
│   └── index.ts
└── index.ts
```
And `//:index` depends on `//foo:index` and `//baz:index`. Assuming that each `.ts` file has it's own associated rule, and the file in the root is importing `foo` and `bar`. How should I create rules for them for `swc` as well as type check? I guess I could run a compile path with only `swc` for stuff I needed in output then `_typecheck` test to check my types but then a `tsc` rule to create the `*.d.ts` files that are needed for the upstream rules. I'm sorry If I'm missing something. 

Obviously, this is a very simple example but have a large number of apps in my project that is broken up and share code so creating a lot of complexity around what should be a dependency to what multiple times courses a lot of headaches. 

https://github.com/swc-project/swc/issues/657

**Comment by alexeagle** [comment] 2022-12-23 21:34
I still don't understand the use case. The only reason you'd need to `select` on the `transpiler` attribute is if some developers want `tsc` to produce their `.js` outputs, while others want `swc` to produce their `.js` outputs. If that were the case, I'd still push back on those developers that diverging the toolchain just increases maintenance burden for repo owners without much benefit.

But I think you're still misunderstanding the current feature. The `transpiler` attribute is not related to type-checking at all. Whatever value you provide to it, `tsc` is still the typechecker and still produces the typings (.d.ts) outputs

**Comment by alexeagle** [comment] 2023-01-07 15:48
It's been a couple weeks so I'll close this, but please comment if you think there's still a missing capability.

**Closed by alexeagle** 2023-01-07 15:48 UTC
Labels: enhancement, question, need: more info

**Comment by matthewjh** [comment] 2023-02-04 18:00
I need this, too, @alexeagle. My use case is a need to support different paths for deriving .js and .d.ts files:

1. With tsc (for d.ts) and swc (for .js) via `transpiler` attr. This is faster and will be used for local development builds.
3. With Angular Compiler. This is slower, but needs to be used for "prod" builds as well as for picking up errors from ngc.

My ideal, cleanest implementation is to have a single call to `ts_project`, with `select`s on `transpiler` and `tsc` to insert the right values based on a build flag `--//:use-ngc`. Given this isn't possible at the moment, I'll have to try to achieve the same ultimate effect with multiple rules.

**Comment by alexeagle** [comment] 2023-02-04 20:19
Yeah I would think you'd always model that as a pair of targets.

The problem with changing configurations is that you overwrite the bazel-out folder (unless you use flags to make the config value affect the bazel-out/path). If you build with ngc on, then build with it off, you don't want to invalidate all the build outputs for "ngc on".
Note that if you did want to use configurations, you could just use `--compilation_mode=opt` for the ngc build and `--compilation_mode=fastbuild` for dev. That has the nice shorthand of `bazel build -c opt`.

Of course, separate targets means you need distinct output paths, so it's not purely better.

I'm curious, it seems like you're really asking for Angular to support a faster swc-based dev mode. Is there some upstream issue for that?

**Comment by matthewjh** [comment] 2023-02-04 22:09
How would you model this without using configurations? Even if I use separate ts_project rules to work around `transpiler` being entangled with macro evaluation, I still need `select`s based on configuration to have downstream `npm_package`s link either the swc or the ngc files, globally. Downstream rules need to consume the JS files through the same targets, regardless.

It seems like a good fit for configurations because it is a modification of how certain parts of the graph are built, but without affecting what is built or the interdependencies between nodes on the graph.

> I'm curious, it seems like you're really asking for Angular to support a faster swc-based dev mode. Is there some upstream issue for that?

https://github.com/angular/angular/issues/43165 is the closest thing I am aware of. It mentions SWC and seems, in any case, to be a prerequisite of what you mention.

**Comment by alexeagle** [comment] 2023-02-04 22:38
I guess you'd need to write a transpiler function that reads the configuration value then. Our swc rule is composed from a struct so that you can recompose it. Does that work?
