### ISSUE TITLE
Project references fail to build when not clean

### ISSUE THREAD

**Issue by rc-glean** [aspect-build/rules_ts#186] opened 2022-10-22 01:42 UTC
It seems like project references can only build from a clean workspace. Any non-exact future builds will fail

Error:
```
bazel build //examples/project_references/lib_a:lib_a

INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Analyzed target //examples/project_references/lib_a:lib_a (2 packages loaded, 332 targets configured).
INFO: Found 1 target...
ERROR: /Users/ray/workspace/rules_ts/examples/project_references/lib_a/BUILD.bazel:15:11: output 'examples/project_references/lib_a/lib_a.tsbuildinfo' was not created
ERROR: /Users/ray/workspace/rules_ts/examples/project_references/lib_a/BUILD.bazel:15:11: Compiling TypeScript project //examples/project_references/lib_a:lib_a [tsc -p examples/project_references/lib_a/tsconfig.json] failed: not all outputs were created or valid
Target //examples/project_references/lib_a:lib_a failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.393s, Critical Path: 0.25s
INFO: 18 processes: 8 internal, 9 local, 1 worker.
FAILED: Build did NOT complete successfully
```

Repro steps:

`git clone https://github.com/aspect-build/rules_ts`
`cd rules_ts`
`bazel build //examples/project_references/lib_a:lib_a # works`
`bazel build //examples/project_references/lib_a:lib_a # works because caches are exact`
`bazel build --action_env="avariable=1" //examples/project_references/lib_a:lib_a # force an unexact rebuild. Fails`
`bazel build //examples/project_references/lib_a:lib_a # will now always fail too`
`bazel clean`
`bazel build //examples/project_references/lib_a:lib_a # works again`

 --verbose_failures shows no additional debug info

I'm using an M1 mac if that matters. I haven't ruled out that something else is wrong with my set up. Happy to gather more debug info if there's methods other than verbose_failures

**Comment by thesayyn** [comment] 2022-10-24 13:57
I can reproduce the issue. Possibly a duplicate of #128

**Comment by rc-glean** [comment] 2022-10-24 17:28
Thank you so much Sahin. Just wanted to kudo: between you, Ben, and Alex, that I'm super impressed with how fast everyone at Aspect responds to and fixes issues

**Closed** 2022-10-28 17:12 UTC
Labels: bug, duplicate
